project_name: CNC
before:
  hooks:
    - go mod tidy

builds:
  - id: main
    flags:
      - -v
      - -trimpath
    asmflags:
      - all=-trimpath=/home/runner/go
    gcflags:
      - all=-trimpath=/home/runner/go
    ldflags:
      - -X github.com/mobeicanyue/Campus-Network-Master-Go/constant.Version={{ .Version }} -s -w -buildid=
    env:
      - CGO_ENABLED=0
    targets:
      - linux_386
      - linux_amd64_v1
      - linux_amd64_v3
      - linux_arm64
      - linux_arm_7
      - windows_amd64_v1
      - windows_amd64_v3
      - windows_386
      - windows_arm64
      - darwin_amd64_v1
      - darwin_amd64_v3
      - darwin_arm64

snapshot:
  name_template: "{{ .Version }}.{{ .ShortCommit }}"

archives:
  - builds:
      - main
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - LICENSE
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
source:
  enabled: false
  name_template: '{{ .ProjectName }}-{{ .Version }}.source'
  prefix_template: '{{ .ProjectName }}-{{ .Version }}/'
checksum:
  disable: true
  name_template: '{{ .ProjectName }}-{{ .Version }}.checksum'
