name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Cross build for Campus-Network-Connection
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Set up and run Goreleaser
        uses: goreleaser/goreleaser-action@v5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List files in working directory
        run: ls -R
